program: ../trainer.py
project: gridrl
method: random
parameters:
  algo:
    type:
      value: ppo
    policy:
      hidden_sizes:
        values:
          - - 32
            - 32
          - - 64
            - 64
    ppo:
      tanhnormal:
        values: [true, false]
      params:
        center_adv:
          values: [true, false]
    rnd:
      intrinsic_reward_weight:
        values: [0.0, 0.01, 0.1, 0.5]
        probabilities: [0.4, 0.2, 0.2, 0.2]
      predictor_lr:
        distribution: log_uniform_values
        min: 1.0e-6
        max: 1.0e-1
      hidden_sizes:
        values:
          - [32, 32]
          - [64, 64]
  env:
    domain_randomization:
      noise_std:
        values: [0.0, 0.05, 0.25, 0.5]
        probabilities: [0.4, 0.2, 0.2, 0.2]
    observation_keys:
      values:
        - ['soc', 'net_load']
        - ['soc', 'net_load', 'import_price_current']
        - ['soc', 'net_load', 'import_price_current', 'import_price_forecast_0', 'import_price_forecast_1']
        - ['soc', 'net_load', 'import_price_current', 'import_price_forecast_0', 'import_price_forecast_1', 'import_price_forecast_2', 'import_price_forecast_3']
        - ['soc', 'net_load', 'import_price_current', 'import_price_forecast_0', 'import_price_forecast_1', 'import_price_forecast_2', 'import_price_forecast_3', 'import_price_forecast_4', 'import_price_forecast_5']
  microgrid:
    config:
      scenario:
        value: 10
    attributes:
      reward_shaping_func:
        values:
          - '!BaselineShaper {module: [grid,0]}'
          - '!BaselineShaper {module: [grid,0], relative_to: true}'
          - '!SequentialShaper {shapers: [!BaselineShaper {module:[grid,0]}, !LearnedScaleRescaleShaper {} ]}'
        probabilities: [0.5, 0.25, 0.25]
metric:
  name: Test/MPCRelativeRewardSum
  goal: minimize
  target: 0.8
command:
  - ${envvar:CONDA_PREFIX}/bin/python
  - ${program}
  - "--config"
  - "general_config.yaml"
  - ${args}
meta:
  wandb_setup:
    api_key_file: ../local/wandb_api_key.txt
    username: ahalev
  sweep_id: null
  launch_agent: false
