env:
  cls: DiscreteMicrogridEnv
  config:
    scenario: 0
algo:
  package: garage
  sampler:
    type: ray
    n_workers: 16
  policy:
    hidden_sizes:
      - 8
      - 5
    exploration:
      decay_ratio: 0.5
      max_epsilon: 1.0
      min_epsilon: 0.05
  dqn:
    buffer_batch_size: 32
    buffer_size: 200000
    clip_gradient: 10
    discount: 0.99
    double_q: false
    lr: 0.0001
    min_buffer_size:
    n_train_steps: 500
    steps_per_epoch: 32
    target_update_freq: 2
  train:
    batch_size: 10000
    n_epochs: 100
log:
  experiment_name: null
  log_dir: experiments
  snapshot_gap: 50