wandb_version: 1

algo.policy.hidden_sizes:
  value:
  - 32
  - 32
algo.ppo.params.center_adv:
  value: false
algo.ppo.tanhnormal:
  value: false
algo.rnd.hidden_sizes:
  value:
  - 64
  - 64
algo.rnd.intrinsic_reward_weight:
  value: 0.01
algo.rnd.predictor_lr:
  value: 0.0004909828841474327
algo.type:
  value: ppo
env.domain_randomization.noise_std:
  value: 0.25
env.observation_keys:
  value:
  - soc
  - net_load
  - import_price_current
  - import_price_forecast_0
  - import_price_forecast_1
microgrid.attributes.reward_shaping_func:
  value: '!SequentialShaper {shapers: [!BaselineShaper {module:[grid,0]}, !LearnedScaleRescaleShaper
    {} ]}'
microgrid.config.scenario:
  value: 10
