wandb_version: 1

algo.policy.hidden_sizes:
  value:
  - 64
  - 64
algo.ppo.params.center_adv:
  value: false
algo.ppo.tanhnormal:
  value: true
algo.rnd.hidden_sizes:
  value:
  - 32
  - 32
algo.rnd.intrinsic_reward_weight:
  value: 0
algo.rnd.predictor_lr:
  value: 0.00047146210153576354
algo.type:
  value: ppo
env.domain_randomization.noise_std:
  value: 0
env.observation_keys:
  value:
  - soc
  - net_load
  - import_price_current
  - import_price_forecast_0
  - import_price_forecast_1
microgrid.attributes.reward_shaping_func:
  value: '!BaselineShaper {module: [grid,0]}'
microgrid.config.scenario:
  value: 10
